# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Set working directory
WORKDIR /app

# Copy package files
COPY package.json package-lock.json ./

# Install dependencies
RUN npm install --ignore-scripts

# Copy remaining source
COPY . .

# Build the TypeScript project
RUN npm run build


# Set default environment variables (can be overridden at runtime)

# Start the MCP server
CMD ["node", "build/index.js"]
